# Generated by Django 4.2.30 on 2026-04-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_ban_reason_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='wants_to_be_author',
            field=models.BooleanField(default=False),
        ),
    ]
